version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:3.4
    ports:
      - "4566:4566"   # Main localstack gateway
      - "4571:4571"   # SES SMTP mock
    environment:
      - SERVICES=dynamodb,dynamodbstreams,lambda,ses,sqs,sns,iam
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - AWS_DEFAULT_REGION=ap-southeast-2
      # Enable TTL deletions
      - DYNAMODB_REMOVE_EXPIRED_ITEMS=1
    volumes:
      - "./localstack:/var/lib/localstack"
      # to mount init scripts for db table creation
      - "./localstack-init:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"

